# Generated by Django 3.0.5 on 2020-04-26 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shutterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='name',
        ),
        migrations.AddField(
            model_name='professional',
            name='additional_info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='genre',
            field=models.CharField(blank=True, choices=[('beauty', 'Красота'), ('fashion', 'Мода'), ('studio', 'Студия'), ('street', 'Улица'), ('fashionShows', 'Показ мод'), ('filming', 'Киносъёмки'), ('clothes', 'Одежда'), ('lingerie', 'Бельё'), ('sports', 'Спорт'), ('erotic', 'Эротика')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='kindOfWork',
            field=models.CharField(blank=True, choices=[('price', 'За оплату'), ('free', 'Бесплатно'), ('creativeProject', 'Творческий проект')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='profession',
            field=models.CharField(choices=[('model', 'Модель'), ('photographer', 'Фотограф'), ('visagiste', 'Визажист')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='sex',
            field=models.CharField(blank=True, choices=[('man', 'Мужчина'), ('woman', 'Женщина')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='userInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professional',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
