# Generated by Django 3.0.5 on 2020-04-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shutterapi', '0002_auto_20200426_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='userInfo',
        ),
    ]
