# Generated by Django 3.0.5 on 2020-04-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterapi', '0005_auto_20200426_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='userFrom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='userTo',
            field=models.IntegerField(null=True),
        ),
    ]
