# Generated by Django 3.0.5 on 2020-04-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterapi', '0006_auto_20200426_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='publications',
            field=models.ManyToManyField(to='shutterapi.Publication'),
        ),
    ]
