# Generated by Django 3.0.5 on 2020-04-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterapi', '0007_auto_20200426_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='professional',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='professional',
            name='genre',
            field=models.ManyToManyField(to='shutterapi.Genre'),
        ),
    ]
