# Generated by Django 3.0.5 on 2020-04-28 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shutterapi', '0008_auto_20200426_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('direction', models.CharField(blank=True, choices=[('photoshoot', 'Фотосессии'), ('impressions', 'Показы'), ('agencies', 'Агентства'), ('advertising', 'Реклама'), ('filming', 'Киносъёмки')], max_length=64, null=True)),
                ('userInfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
