# Generated by Django 3.0.5 on 2020-04-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterapi', '0011_auto_20200429_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='userFrom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='userTo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='shutterapi.Genre'),
        ),
    ]
