# Generated by Django 3.0.5 on 2020-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterapi', '0012_auto_20200429_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
